name: pyTMB
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.6.10
  - bioconda::cyvcf2=0.11.7
  - conda-forge::pyyaml=5.3.1
  - bioconda::mosdepth=0.2.6
  - bioconda::pybedtools=0.8.1

#an example of an enviroment.yml from https://github.com/bioinfo-pf-curie/TMB
